version: '3'

tasks:
  dev:
    cmds:
      - npm run dev
  build:
    cmds:
      - npm run build
  lint:
    cmds:
      - npm run lint
  test:
    cmds:
      - npm test
  typecheck:
    cmds:
      - npm run typecheck
  check:
    cmds:
      - npm run check
